#!/usr/bin/env node
/**
 * Prebuild script: generates src/core/version.ts from package.json + git metadata.
 * Run automatically via "prebuild" in package.json.
 */

import { execSync } from "node:child_process";
import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const root = dirname(dirname(fileURLToPath(import.meta.url)));
const pkg = JSON.parse(readFileSync(join(root, "package.json"), "utf8"));

function gitRevision() {
  try {
    return execSync("git rev-parse --short HEAD", { cwd: root, stdio: ["ignore", "pipe", "ignore"] })
      .toString()
      .trim();
  } catch {
    return "unknown";
  }
}

const version = pkg.version;
const commit = gitRevision();
const buildDate = new Date().toISOString();

const content = `// AUTO-GENERATED by scripts/generate-version.mjs — do not edit by hand.
// Regenerated on every build via the "prebuild" npm script.
export const VERSION = ${JSON.stringify(version)};
export const COMMIT = ${JSON.stringify(commit)};
export const BUILD_DATE = ${JSON.stringify(buildDate)};
`;

const outPath = join(root, "src", "core", "version.ts");
writeFileSync(outPath, content, "utf8");
console.log(`Generated ${outPath} (v${version}, ${commit})`);
